[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # color scheme
repo = 'rebelot/kanagawa.nvim'
hook_add = '''
colorscheme kanagawa
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'junegunn/fzf'
merged = 0
build = '''
./install --all
'''
